# Generated by Django 4.2.28 on 2026-02-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"verbose_name": "Производитель"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name": "Поставщик"},
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="phone",
        ),
        migrations.AddField(
            model_name="product",
            name="SKU",
            field=models.CharField(
                default=0, max_length=20, unique=True, verbose_name="Артикул"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_type",
            field=models.CharField(
                default="шт.", max_length=20, verbose_name="Единица измерения"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Скидка %"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Фото (имя файла)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.IntegerField(default=0, verbose_name="Количество на складе"),
        ),
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
        migrations.AlterModelTable(
            name="manufacturer",
            table="manufacturer",
        ),
        migrations.AlterModelTable(
            name="product",
            table="product",
        ),
        migrations.AlterModelTable(
            name="supplier",
            table="supplier",
        ),
    ]
